// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using UnityEngine;
public class AlcoholBehaviour : FoodBehaviour
{
	public static float StrengthFactor = 2.0f;
	public static float SpeedFactor = 0.006f;
	public static float PoisonAmount = 100.0f;

	// Use this for initialization
	void Start () {
		health = 0;
		(this.GetComponent("SpriteRenderer") as SpriteRenderer).sprite = Resources.Load<Sprite> ("beer");
	}
	
	// Update is called once per frame
	void Update () {
		
	}
}
