// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using UnityEngine;

public class FoodBehaviour : MonoBehaviour
{
	public float amountOfFood { get; set; }
	public float pointsForEating { get; set; }
	public float health { get; set; }

	// Use this for initialization
	void Start () {
	}
	
	// Update is called once per frame
	void Update () {
		
	}

	void hit(GameObject go, float amount) {
		health -= amount;
		if (health <= 0) {
			go.SendMessage("foodDied", this);
		}
	}
}

