// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using UnityEngine;

public class PlayerAI : MonoBehaviour
{
	PATileTerrain terrain;
	float _health;

	public PlayerAI() {
		speed = 2.0f;
		numberOfUpgrades = 0;
		PlantBehaviour.Points = 65;
		PlantBehaviour.Food = 5;
		MeatBehaviour.Points = 110;
		MeatBehaviour.Food = 10;
		points = 100;

		meatDesire = 0.1f;
		plantDesire = 0.1f;
	}

	public float points { get; set; }
	public float health { get {
			return _health;
		}
		set
		{ 
			_health = Mathf.Min(value, maxHealth);
		}
	}
	public int numberOfUpgrades { get; set; }
	public float speed { get; set; }
	public float strength { get; set; }
	public float plantDistance { get; set; }
	public float meatDistance {get; set;}
	public float maxHealth { get; set; }
	public float plantDesire {get; set;}
	public float meatDesire { get; set; }

	public Vector3 moveDirection;
	float timeToChangeMoveDirection;
	float timeBetweenAttacks = 1.0f;
	float attackInitialIntercal = 1.0f;

	float attackDistance = 1;
	
	float changeInterval = 5.0f;
	
	// Use this for initialization
	void Start () {
		moveDirection = this.randomMoveDirection ();

		GameObject go = GameObject.Find("Tile Map");
		if (go != null) terrain = go.GetComponent<PATileTerrain>();
		plantDistance = 10;
		meatDistance = 10;
		strength = 0;
		maxHealth = 100;
		health = 100;
	}
	
	// Update is called once per frame
	void Update () {
		this.updateHealth();
		this.movePlayer();
	}

	void updateHealth() {
		health -= numberOfUpgrades * Time.deltaTime;
		if (health <= 0) {
			this.SendMessage ("playerDead");
			return;
		}
	}
	
	void movePlayer() {
		transform.localPosition += moveDirection * Time.deltaTime * this.speed;
		timeToChangeMoveDirection -= Time.deltaTime;
		if (terrain == null) {
			GameObject go = GameObject.Find("Tile Map");
			if (go != null) terrain = go.GetComponent<PATileTerrain>();
		}

		GameObject nearestPlant = this.nearestObjectWithTag("PlantBehaviour");
		Vector3 nearestPlantDirection = new Vector3();
		if (nearestPlant != null) {
			nearestPlantDirection = nearestPlant.transform.localPosition - transform.localPosition;
			nearestPlantDirection.y = 0;
		}

		GameObject nearestMeat = this.nearestObjectWithTag ("MeatBehaviour");
		Vector3 nearestMeatDirection = new Vector3();
		if (nearestMeat != null) {
			nearestMeatDirection = nearestMeat.transform.localPosition - transform.localPosition;
			nearestMeatDirection.y = 0;
		}
		
		float distanceToPlant = nearestPlantDirection.sqrMagnitude;
		float distanceToMeat = nearestMeatDirection.sqrMagnitude;

		if (nearestMeat != null && nearestPlant != null) {
			if (meatDesire >= plantDesire) {
				this.attackObject(nearestMeat, nearestMeatDirection.normalized, distanceToMeat);
			} else {
				this.attackObject(nearestPlant, nearestPlantDirection.normalized, distanceToPlant);
			}
		} else if (nearestPlant != null && distanceToPlant < plantDistance * plantDistance) {
			this.attackObject(nearestPlant, nearestPlantDirection.normalized, distanceToPlant);
		} else if (nearestMeat != null && distanceToMeat < meatDistance * meatDistance) {
			this.attackObject(nearestMeat, nearestMeatDirection.normalized, distanceToMeat);
		} else if (timeToChangeMoveDirection <= 0) {
			changeMoveDirection();
		} else if (transform.localPosition.x <= 0 || transform.localPosition.x >= terrain.width ||
		           transform.localPosition.z <= 0 || transform.localPosition.z >= terrain.height) {
			print ("out of bounds");
			moveDirection *= -1;
			timeToChangeMoveDirection = changeInterval;
		}

	}

	GameObject nearestObjectWithTag(string name) {
		GameObject[] gos = GameObject.FindGameObjectsWithTag(name);
		GameObject nearestPlant = null;
		foreach (GameObject go in gos) {
			if (nearestPlant == null) {
				nearestPlant = go;
			} else {
				Vector3 oldDistance = nearestPlant.transform.localPosition - transform.localPosition;
				Vector3 newDistance = go.transform.localPosition - transform.localPosition;
				if (newDistance.sqrMagnitude < oldDistance.sqrMagnitude) {
					nearestPlant = go;
				}
			}
		}
		return nearestPlant;
	}

	void attackObject (GameObject go, Vector3 direction, float distance) {
		timeToChangeMoveDirection = changeInterval;
		moveDirection = direction;
		
		timeBetweenAttacks -= Time.deltaTime;
		if (distance < attackDistance && timeBetweenAttacks <= 0) {
			timeBetweenAttacks = attackInitialIntercal;
			go.SendMessageUpwards ("Attack", this.gameObject);
		}
	}
	
	void changeMoveDirection() {
		timeToChangeMoveDirection = changeInterval;
		moveDirection = this.randomMoveDirection ();
	}
	
	Vector3 randomMoveDirection() {
		float velocityX = Random.Range(-1000, 1000);
		float velocityZ = Random.Range(-1000, 1000);
		return new Vector3(velocityX, 0, velocityZ).normalized;
	}
	
	void playerDead() {
		Application.LoadLevel ("game over");
	}

	void killed(GameObject go) {
		if (go.tag.Equals ("PlantBehaviour")) {
			this.points += PlantBehaviour.Points;
			this.health += PlantBehaviour.Food;
			this.health = Mathf.Min(this.health, this.maxHealth);
		} else if (go.tag.Equals ("MeatBehaviour")) {
			this.points += MeatBehaviour.Points;
			this.health += MeatBehaviour.Food;
			this.health = Mathf.Min(this.health, this.maxHealth);
		}
	}
}


